services:
  postgres:
    container_name: debezium-postgres
    image: debezium/postgres:15
    ports: ["5432:5432"]
    command: postgres -c wal_level=logical -c max_wal_senders=10 -c max_replication_slots=10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orderdb
    restart: no
    networks:
      - kafka-net

  zookeeper:
    container_name: zookeeper
    image: quay.io/debezium/zookeeper:3.1
    ports:
      - "2181:2181"
    restart: no
    networks:
      - kafka-net

  kafka:
    container_name: debezium-kafka
    image: quay.io/debezium/kafka:3.1
    depends_on: [ zookeeper ]
    ports: [ "29092:29092" ]
    restart: no
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-net

  connect:
    container_name: debezium-connect
    image: quay.io/debezium/connect:3.1
    depends_on: [ kafka ]
    ports: [ "8083:8083" ]
    restart: no
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
    networks:
      - kafka-net

  debezium-ui:
    container_name: debezium-ui
    image: quay.io/debezium/debezium-ui:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_CONNECT_URIS: http://connect:8083
    restart: no
    depends_on:
      - connect
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge