scrape_configs:
  - job_name: 'AppMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8181']
        labels:
          application: 'Order-service'